name: Intercom (JoeHogan/ha-intercom)
slug: ha_intercom
description: Run the ha-intercom FFmpeg/Node intercom server with Home Assistant Ingress.
version: 0.1.1
stage: experimental
url: https://github.com/JoeHogan/ha-intercom
arch:
  - aarch64
  - amd64
  - armv7
startup: services
panel_icon: mdi:account-voice
ingress: true
ingress_port: 3001
ingress_stream: true
ports:
  3001/tcp: null
ports_description:
  3001/tcp: Optional — expose service on host (not required for Ingress)
hassio_api: true
homeassistant_api: true
privileged:
  - SYS_ADMIN
  - NET_ADMIN
map:
  - media:rw
  - share:rw
  - config:rw
options:
  host: 0.0.0.0
  port: 3001
  whisper_host: 0.0.0.0
  whisper_port: 9000
  ha_url: "http://supervisor/core"
  ha_token: ""
  tts_prefix: "say"
  extra_env: []
schema:
  host: str
  port: int
  whisper_host: str
  whisper_port: int
  ha_url: str
  ha_token: str
  tts_prefix: str
  extra_env:
    - str
